// use this quizData in your app.
export const quizData = [
  {
    question: "Which language runs in a web browser?",
    a: "Java",
    b: "C",
    c: "Python",
    d: "JavaScript",
    correct: "d",
  },
  {
    question: "What does CSS stand for?",
    a: "Central Style Sheets",
    b: "Cascading Style Sheets",
    c: "Cascading Simple Sheets",
    d: "Cars SUVs Sailboats",
    correct: "b",
  },
  {
    question: "What does HTML stand for?",
    a: "Hypertext Markup Language",
    b: "Hypertext Markdown Language",
    c: "Hyperloop Machine Language",
    d: "Helicopters Terminals Motorboats Lamborginis",
    correct: "a",
  },
  {
    question: "What year was JavaScript launched?",
    a: "1996",
    b: "1995",
    c: "1994",
    d: "none of the above",
    correct: "b",
  },
  {
    question: "Which company developed the React library?",
    a: "Google",
    b: "Facebook",
    c: "Microsoft",
    d: "Amazon",
    correct: "b",
  },
  //   {
  //     question: "What does API stand for?",
  //     a: "Application Programming Interface",
  //     b: "Advanced Programming Integration",
  //     c: "Application Program Internet",
  //     d: "Applied Programming Instruction",
  //     correct: "a",
  //   },
  //   {
  //     question: "Which HTML tag is used to define an unordered list?",
  //     a: "<ol>",
  //     b: "<ul>",
  //     c: "<li>",
  //     d: "<list>",
  //     correct: "b",
  //   },
  //   {
  //     question: "Which of the following is a NoSQL database?",
  //     a: "MySQL",
  //     b: "PostgreSQL",
  //     c: "MongoDB",
  //     d: "Oracle",
  //     correct: "c",
  //   },
  //   {
  //     question: "Inside which HTML element do we put the JavaScript?",
  //     a: "<javascript>",
  //     b: "<js>",
  //     c: "<script>",
  //     d: "<code>",
  //     correct: "c",
  //   },
  //   {
  //     question: "Which symbol is used for comments in JavaScript?",
  //     a: "//",
  //     b: "/* */",
  //     c: "#",
  //     d: "<!-- -->",
  //     correct: "a",
  //   },
  //   {
  //     question: "Which method converts JSON data to a JavaScript object?",
  //     a: "JSON.toObject()",
  //     b: "JSON.parse()",
  //     c: "JSON.stringify()",
  //     d: "JSON.convert()",
  //     correct: "b",
  //   },
  //   {
  //     question: "Which one is a JavaScript framework?",
  //     a: "Django",
  //     b: "Laravel",
  //     c: "React",
  //     d: "Flask",
  //     correct: "c",
  //   },
  //   {
  //     question: "What is the correct file extension for JavaScript files?",
  //     a: ".java",
  //     b: ".js",
  //     c: ".javascript",
  //     d: ".jsx",
  //     correct: "b",
  //   },
  //   {
  //     question: "Which CSS property controls the text size?",
  //     a: "font-style",
  //     b: "text-size",
  //     c: "font-size",
  //     d: "text-style",
  //     correct: "c",
  //   },
];
